name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.10']

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry --version
          poetry config virtualenvs.in-project true
          
      - name: Install Project
        run: poetry install -vv
      
      - name: Look for style errors
        run: poetry run flake8 .
      
      - name: Look for auto format errors
        run: poetry run black -l 79 --check --diff .
