name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Display Python version
        run: python --version

      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry --version
          poetry config virtualenvs.in-project true

      - name: Install Project
        run: poetry install

      - name: Look for style errors
        run: poetry run flake8 .

      - name: Look for auto format errors
        run: poetry run black -l 79 --check --diff .